"""add outbox table

Revision ID: 44fb3986cc7b
Revises: 7dafe3b051d8
Create Date: 2026-09-22 20:56:59.521116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fb3986cc7b'
down_revision: Union[str, Sequence[str], None] = '7dafe3b051d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('op', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assignment', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('so_line_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('odoo_line_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("op in ('create','update','delete')", name='outbox_op_check'),
    sa.CheckConstraint("state in ('pending','synced','failed')", name='outbox_state_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_employee_pending', 'outbox', ['employee_id', 'entry_date'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index('ix_outbox_state_next_attempt', 'outbox', ['state', 'next_attempt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_state_next_attempt', table_name='outbox')
    op.drop_index('ix_outbox_employee_pending', table_name='outbox', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('outbox')
    # ### end Alembic commands ###
